const actionTypes = {
    FETCH_NEWS_DATA_INITAITE:"FETCH_NEWS_DATA_INITAITE",
    FECTH_NEW_DATA_SUCCESSFUL:'FECTH_NEW_DATA_SUCCESSFUL',
    FETCH_NEW_DATA_ERROR:'FETCH_NEW_DATA_ERROR',
    SELECTED_NEWS:'SELECTED_NEWS'
}
export default actionTypes;
